copypastas = [
    
    "<h2>Avengers Infinity War Spoilers:</h2> The way my dad set up my wii it turned me on... I couldn't help but to grab his ass he looked at me with seductive eyes i pulled my pants down and started fucking my dads ass he was enjoying it as much as i did but to my surprise his asshole was loose but then my pet dog walked in and bit my nuts and my dads we stopped before my mother walked in...",

    "<h2>I'm drooling,</h2> I'm literally shedding my former self and ascending at just the mere sight of this girl. My simp levels have reached an unspeakable high, I am terrified I might destroy the universe if I see any more of her. I'm not scared for the universe, I'm scared of killing each and every precious woman on this horrible man-fllled planet. My penis has just reached a new height, hitting 3 inches. I can already feel the essence of time ripping apart with each and every breath ltake. I must ascend, so this girl will live in peace. Goodbye, fellow simps.",
    
    "<h2>Egg nog</h2>This reminds me of the days when you could poor egg nog on your balls; it's just not the same anymore, my balls now cannot be covered in the delicious drink because my dog licks the egg nog off so I can't feel the creamy nutmeg cinnamon egg based drink around my balls; for anyone going through a hard time like me it gets better.",
    
    "<h2>Nice opinion.</h2>Just one tiny problem with it. Inspecting your post, it looks like your opinion is different from mine.<br><br>Boy, let me tell you something.<br><br>I am the baseline for opinions, any opinion I hold is objectively correct and, as a result, any other opinions are wrong. And guess what? You happen to hold a wrong one. And I hope you know that your opinion is now illegal. I have now contacted the FBI, the CIA, the NSA, the Navy SEALs, the Secret Service and your mom. You'll rot in prison for the rest of your life over this, mark my words you'll be sorry you ever shared your opinions. By the time you're reading this, you're done for boy. Nature will punish you. Humanity will punish you. Supernatural beings will punish you. Space will punish you. Oh yeah, and we decided that just to make sure we'll nuke your house from orbit so there's no chance you can run away and everyone you know will die. It's a small price to pay for ethnic cleansing. May this post be a warning for anyone else brave enough to share an incorrect opinion; you've been warned.",
    
    "<h2>Hi,</h2>I'm an engineering student and i build my car, I'm learning how to make electrical systems and all that. Right now, I'm working on a General Positioning System (GPS) so that I may be able to locate the person who asked you.",
    
    "<h2>THE NINTENDO SWITCH FUCKING SUCKS</h2><h3>Chapter 1: Prologue</h3>The goddamn Nintendo Nintendo has taken the gaming market by storm, selling rapidly fast and projected just under the PS4 which isn't exactly as small feat considering the PS4 is projected to sell past the PS2 which is the best sold video game console of all time. Not too shabby, Nintendo and Sony. As much as I'd love to go into the PS4 right now, I'll be saving that for a later date so back to Nintendo. As previously mentioned, those numbers are not small by any stretch of the imagination and is fueling Nintendo with the money needed to come back into the video game industry alive and kicking, or more accurately, with enough money to be a subject of gloating for the people that will. A lot of fans, critics, and casuals have exemplified the Switch as a console that proves graphics do not hold supreme and that games just need to be fun to be played. So naturally I took the liberty of picking one up to see for myself. After months of hands-on-experience with the Switch I have but one question: Why? When I ask the people what word they think of the Switch and Nintendo these days with the launch of the Switch I get 1 response far more than any other: \"Innovative.\" The first word I can think of is \"visionary.\" These words may sound like synonyms to an absolute idiot but to anyone that pays attention to basic shit knows that these words are very different and the latter is not exactly a glowing recommendation considering how common it is. Innovation isn't daring to be different, it's pioneering something that will change everything. Being a visionary is seeing what is needed by the masses, and giving it to them. Innovation and vision can be linked, but in the case of Nintendo it rarely is. Take the Switch for example, do you really think Nintendo was the first person to come up with the idea of putting home console-like quality on the go? In recent memory, Sony did that first with the PSP and the Vita. But I suppose the real \"innovative\" part of the equation is the Switch dock which allows the Switch to be connected to the TV as well, making it work as both a handheld and a home console. Not only did the PSP do this, and to some degree the Vita, the Sega Nomad was the very first to do this to exact same degree of the Switch about 26 years ago. That's right, Nintendo isn't just late to the party, they're 26 years late to the party. The stuff about Nintendo innovating with the Switch is simply bullshit, they figured that another hybrid was what the industry needed and they were right. This is being a visionary, not an innovator.",
    
    "<h2>Jacob</h2>Let me tell you a story about my son, Jacob. We always said his eyes are like floodlights. Everything he saw and touched became illuminated to those around him, their forgotten childhoods suddenly springing forth as they rediscovered the funny shapes of things, the optimistic guesses at how the world must work, or the way a squirrel obscured by rain looks like it's flying when it runs along a powerline. We remembered what joy is, the way it feels when you're too young to understand that it comes and goes. These were the things Jacob shared with us, and I can't imagine going back.<br><br>Jacob wanted a youtube channel, and so we made it for him. Janet had worked as a camera operator back when we had jobs, so she handled the technical aspects. Sidney wrote for a blog, so she helped steer Jacob's creativity. David worked in the NICU and was there when Jacob opened his eyes for the first time. My job was to make sure Jacob never, ever got upset. That had happened before, and we all got very upset as well. It was unpleasant, and his mother Emily had to leave us because of it.<br><br>The love that Jacob received for his channel was astounding, and not entirely unexpected. He wanted us to give him gigantic chocolate eggs filled with toys, and so we did. His \"M&M Spaghetti\" video received more views than \"Despacito\". His reach grew around the world. Those pure eyes stealing everyone they gazed upon, never upset, through cell phones and social media -- late night talk shows segments and finally a meeting with the president.<br><br>I can't believe how much he's grown in the years since. To achieve so much at such a young age would be a strain on anyone, but I never let him get upset. He doesn't want youtube channels anymore. He's much more important than that, and whatever he wants... he gets. I knew that the moment he looked in my eyes for the first time. I'd do anything for Jacob, and sometimes I have. <b>But I'd still kick Jacob off a fucking bridge if it means that you didn't post that.</b>",

    "<h2>My Big Cock</h2>my cock is so fucking big that it weighs me down, i have scoliosis because of my extemely large penis. my cock is so unbelievably huge that if gravity stopped working i'd still be on the ground",

    "<h2>According to world population studies,</h2> approximately 108 billion people have lived on this planet. Assuming that the average lifespan of all these people was 25, there has been around 2.7 trillion years of life, if we multiply this by the number of days in a year (365), there is a total of 985,500,000,000,000 days of life (985.5 trillion days). Not once in any of those days did anybody ask...",

    "<h2>Hey I got a question,</h2>uhh what if you’re wrong? What if the thousands of doctors and health organizations warning you that drinking this stuff damages your insides actually know what they’re talking about, and you’ve been putting industrial strength cleaning supplies in your body for absolutely nothing that wouldn’t have happened if you just took a sugar pill? And sure I’ll address the logical response from you: “But what if we’re right?” -- well if you’re right and somehow drinking bleach does cure everything from AIDS to bee stings, it’ll still be super dangerous because people have died following your advice in the real world; You know, the place you left far behind when you started spraying bleach on bug bites.<br><br>And yes, I know what you would tell me next you’d be like “Say boy that’s one juicy dick you got there mind if I slap it around with my tongue?” and I would be shocked, unable to really respond. I’d stammer “But we’re in a church…” and you’d put your finger to my lips shushing me as you undo my belt. As we collapse into each other after hours of vigorous love-making, we’d share a knowing glance and you’d whisper “You’re right. It’s not medicine,” and this time I’d shush you saying “I don’t care anymore.”<br><br>Afterwards, I guess we’d go our separate ways, two ships passing in the night. The air outside would be warm and humid like an incubator for one more important question, fresh and exciting, powered by the electricity in the air as if the city knew exactly what mood to dial itself. The question hammers in my head as I hail a cab home: “Man, what is the deal with that stupid fucking hat?”"

]